CREATE TABLE [dbo].[CpapAthlete]
(
[CpapAthleteId] [int] NOT NULL IDENTITY(1, 1),
[PersonId] [int] NOT NULL,
[AccountCreationDate] [datetime] NULL,
[LastLogon] [datetime] NULL,
[NumberOfVisits] [int] NULL,
[UserType] [smallint] NULL,
[AthleteType] [smallint] NULL,
[AthleteTypeDesc] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age] [float] NULL,
[Sex] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AffiliateId] [int] NULL,
[MonthsOnSystem] [smallint] NULL,
[MonthsActiveOnSystem] [smallint] NULL,
[TrialPremiumSubCouponUsed] [bit] NULL,
[AthleteSubscribesToDailyWoEmail] [bit] NULL,
[CoachedByPersonId] [int] NULL,
[BoughtWorkoutPlan] [smallint] NULL,
[BoughtMealPlan] [smallint] NULL,
[CoachSuppliedWorkoutPlan] [smallint] NULL,
[CoachSuppliedMealPlan] [smallint] NULL,
[AtpYearsWithGoals] [smallint] NULL,
[AtpYearsWithObjectives] [smallint] NULL,
[AtpTotalRaceCount] [smallint] NULL,
[AtpAvgAnnualHours] [smallint] NULL,
[WorkoutLibraryCount] [smallint] NULL,
[MealLibraryCount] [smallint] NULL,
[IsHeartRateZoneDefault] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsPowerZoneDefault] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsSpeedZoneDefault] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FitnessSummary] [int] NULL,
[DailyCalories] [int] NULL,
[Macronutrients] [int] NULL,
[GettingStarted] [int] NULL,
[DailyMetrics] [int] NULL,
[DistanceByWeek_Day] [int] NULL,
[DurationByWeek_Day] [int] NULL,
[PMC] [int] NULL,
[PeakPower] [int] NULL,
[TimeinHRZones] [int] NULL,
[FitnessHistory] [int] NULL,
[TSSbyWeekDay] [int] NULL,
[PowerProfile] [int] NULL,
[TimeInHRZonesByWeek] [int] NULL,
[GroceryList] [int] NULL,
[PeakHearRate] [int] NULL,
[TimeInPowerZones] [int] NULL,
[TimeInPowerZonesByWeek] [int] NULL,
[KJPerWeek] [int] NULL,
[RaceReports] [int] NULL,
[WeatherPod] [int] NULL,
[LongestWorkoutDuration] [int] NULL,
[LongestWorkoutDistance] [int] NULL,
[PeakPace] [int] NULL,
[PeakSpeed] [int] NULL,
[PeakCadence] [int] NULL,
[MicroNutrients] [int] NULL,
[RoutesHistory] [int] NULL,
[TimeInSpeedZonesByWeek] [int] NULL,
[TimeInSpeedZones] [int] NULL,
[PeakPaceByDistance] [int] NULL,
[HealthVaultSync] [int] NULL,
[HasCustomizedDashboard] [int] NULL,
[PlannedMealCount] [int] NULL,
[PlannedLoggedMealCount] [int] NULL,
[UnPlannedLoggedMealCount] [int] NULL,
[MonthsAsAPremAthleteCount] [int] NULL,
[ARR] [float] NULL,
[LtsSubscription] [float] NULL,
[LtsTrainingPlan] [float] NULL,
[LtsSoftware] [float] NULL,
[LtsTotal] [float] NULL,
[MostPopularDevice] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalUploads] [int] NULL,
[NumberOfDevices] [int] NULL,
[DateAdded] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CpapAthlete] ADD CONSTRAINT [CpapAthlete_pk] PRIMARY KEY CLUSTERED  ([CpapAthleteId]) WITH (FILLFACTOR=95) ON [PRIMARY]
GO
