CREATE TABLE [dbo].[PayPalProductRevenue]
(
[PersonId] [int] NULL,
[RowOrder] [float] NULL,
[RowType] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AffiliateId] [int] NULL,
[AffiliateCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Username] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AthleteType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsAthlete] [bit] NULL,
[IsAthleteCoached] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AthleteIsCoachedByPersonId] [int] NULL,
[AthleteIsCoachedBy] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zip] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountCreationDate] [datetime] NULL,
[LastLogon] [datetime] NULL,
[ExpireDate] [datetime] NULL,
[NumberOfVisits] [int] NULL,
[AllowMarketingEmails] [bit] NULL,
[Age] [float] NULL,
[Sex] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Language] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UserType] [int] NULL,
[UserTypeDesc] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumberOfCoachedAthletes] [int] NULL,
[NumberOfBasicCoachedAthletes] [int] NULL,
[NumberOfSelfCoachedAthletes] [int] NULL,
[NumberOfPremiumCoachedAthletes] [int] NULL,
[IsThisCoachUBC] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaypalImportId] [int] NOT NULL,
[ZuoraTransactionId] [int] NULL,
[Year] [int] NULL,
[Month] [int] NULL,
[Sku] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanId] [int] NULL,
[Type] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProfileId] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionDate] [datetime] NULL,
[SubscriptionFrom] [datetime] NULL,
[SubscriptionTo] [datetime] NULL,
[SubscriptionMonths] [int] NULL,
[TransDesc] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Total] [float] NULL,
[AvgPerMonth] [float] NULL,
[MonthsActive] [int] NULL,
[Revenue2008] [float] NULL,
[Revenue2009] [float] NULL,
[Revenue2010] [float] NULL,
[Revenue2011] [float] NULL,
[Revenue2012] [float] NULL,
[Revenue2013] [float] NULL
) ON [PRIMARY]
GO
