CREATE TABLE [dbo].[Cpap2013Athlete]
(
[CpapAthleteId] [int] NOT NULL IDENTITY(1, 1),
[PersonId] [int] NOT NULL,
[AccountCreationDate] [datetime] NULL,
[LastLogon] [datetime] NULL,
[NumberOfVisits] [int] NULL,
[UserType] [smallint] NULL,
[AthleteType] [smallint] NULL,
[AthleteTypeDesc] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age] [float] NULL,
[Sex] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AffiliateId] [int] NULL,
[TrialPremiumSubCouponUsed] [bit] NULL,
[AthleteSubscribesToDailyWoEmail] [bit] NULL,
[CoachedByPersonId] [int] NULL,
[AllowMarketingEmails] [bit] NULL,
[ThresholdsNotifyAthlete] [bit] NULL,
[ThresholdsAutoApply] [bit] NULL,
[DaysToPremSub] [int] NULL,
[FirstPremTerm] [int] NULL,
[BoughtWorkoutPlan] [smallint] NULL,
[BoughtNutritionPlan] [smallint] NULL,
[BoughtNutritionAndWorkoutComboPlan] [smallint] NULL,
[BoughtWorkoutLibrary] [smallint] NULL,
[CoachSuppliedWorkoutPlan] [smallint] NULL,
[CoachSuppliedMealPlan] [smallint] NULL,
[AppliedPlanCount] [smallint] NULL,
[AtpYearsWithGoals] [smallint] NULL,
[AtpYearsWithObjectives] [smallint] NULL,
[AtpTotalRaceCount] [smallint] NULL,
[AtpAvgAnnualHours] [smallint] NULL,
[WorkoutsInLibraryCount] [smallint] NULL,
[MealsCreatedByUserCount] [smallint] NULL,
[IsHeartRateZoneDefault] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsPowerZoneDefault] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsSpeedZoneDefault] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FitnessSummary] [int] NULL,
[DailyCalories] [int] NULL,
[Macronutrients] [int] NULL,
[GettingStarted] [int] NULL,
[DailyMetrics] [int] NULL,
[DistanceByWeek_Day] [int] NULL,
[DurationByWeek_Day] [int] NULL,
[PMC] [int] NULL,
[PeakPower] [int] NULL,
[TimeinHRZones] [int] NULL,
[FitnessHistory] [int] NULL,
[TSSbyWeekDay] [int] NULL,
[PowerProfile] [int] NULL,
[TimeInHRZonesByWeek] [int] NULL,
[GroceryList] [int] NULL,
[PeakHearRate] [int] NULL,
[TimeInPowerZones] [int] NULL,
[TimeInPowerZonesByWeek] [int] NULL,
[KJPerWeek] [int] NULL,
[RaceReports] [int] NULL,
[WeatherPod] [int] NULL,
[LongestWorkoutDuration] [int] NULL,
[LongestWorkoutDistance] [int] NULL,
[PeakPace] [int] NULL,
[PeakSpeed] [int] NULL,
[PeakCadence] [int] NULL,
[MicroNutrients] [int] NULL,
[RoutesHistory] [int] NULL,
[TimeInSpeedZonesByWeek] [int] NULL,
[TimeInSpeedZones] [int] NULL,
[PeakPaceByDistance] [int] NULL,
[HealthVaultSync] [int] NULL,
[HasCustomizedDashboard] [smallint] NULL,
[PlannedMealCount] [smallint] NULL,
[PlannedUnLoggedMealCount] [smallint] NULL,
[PlannedLoggedMealCount] [smallint] NULL,
[UnPlannedLoggedMealCount] [smallint] NULL,
[PlannedMealMonths] [smallint] NULL,
[PlannedUnLoggedMealMonths] [smallint] NULL,
[PlannedLoggedMealMonths] [smallint] NULL,
[UnPlannedLoggedMealMonths] [smallint] NULL,
[MonthsOnSystem] [smallint] NULL,
[MonthsOnSystemSince2013] [smallint] NULL,
[MonthsActiveOnSystem] [smallint] NULL,
[MonthsActiveOnSystemSince2013] [smallint] NULL,
[PercentOfMonthsActiveOnSystem] [float] NULL,
[PercentOfMonthsActiveOnSystemSince2013] [float] NULL,
[MonthsAsUserType1] [smallint] NULL,
[MonthsSinceUserType1] [smallint] NULL,
[MonthsAsPaidUserType4] [smallint] NULL,
[ARR] [float] NULL,
[LtsSubscription] [float] NULL,
[LtsTrainingPlan] [float] NULL,
[LtsSoftware] [float] NULL,
[LtsLibrary] [float] NULL,
[LtsTotal] [float] NULL,
[MostPopularDevice] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalUploads] [int] NULL,
[NumberOfDevices] [smallint] NULL,
[EquipmentBikeCount] [smallint] NULL,
[EquipmentShoeCount] [smallint] NULL,
[RouteCount] [smallint] NULL,
[WeightInKilogramsMetric] [smallint] NULL,
[SleepQualityMetric] [smallint] NULL,
[SleepHoursMetric] [smallint] NULL,
[FatigueMetric] [smallint] NULL,
[SorenessMetric] [smallint] NULL,
[StressMetric] [smallint] NULL,
[PulseMetric] [smallint] NULL,
[SleepElevationInMetersMetric] [smallint] NULL,
[OverallFeelingMetric] [smallint] NULL,
[PercentFatMetric] [smallint] NULL,
[LapseCount] [smallint] NULL,
[RenewSaleCount] [smallint] NULL,
[RecurSaleCount] [smallint] NULL,
[DaysSinceLastPremSub] [smallint] NULL,
[FavoriteFoodCount] [smallint] NULL,
[GaAppiOsVisits] [smallint] NULL,
[GaAppAndroidVisits] [smallint] NULL,
[GaWebiOSVisits] [smallint] NULL,
[GaWebAndroidVisits] [smallint] NULL,
[GaWebDesktopVisits] [smallint] NULL,
[GaOtherVisits] [smallint] NULL,
[DateAdded] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Cpap2013Athlete] ADD CONSTRAINT [Cpap2013Athlete_pk] PRIMARY KEY CLUSTERED  ([CpapAthleteId]) WITH (FILLFACTOR=95) ON [PRIMARY]
GO
